[2024-01-07T00:26:33.410+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_department_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-01-07T00:26:33.419+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_department_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-01-07T00:26:33.420+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T00:26:33.448+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_department_Postgres_To_GCS> on 2023-11-28 00:00:00+00:00
[2024-01-07T00:26:33.455+0000] {standard_task_runner.py:57} INFO - Started process 1890 to run task
[2024-01-07T00:26:33.460+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_department_Postgres_To_GCS', 'scheduled__2023-11-28T00:00:00+00:00', '--job-id', '360', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpa56m1zyv']
[2024-01-07T00:26:33.464+0000] {standard_task_runner.py:85} INFO - Job 360: Subtask copy_department_Postgres_To_GCS
[2024-01-07T00:26:33.540+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_department_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [running]> on host f500624b13d0
[2024-01-07T00:26:33.675+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_department_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2023-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-28T00:00:00+00:00'
[2024-01-07T00:26:33.693+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T00:26:33.708+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T00:26:33.744+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T00:26:33.749+0000] {postgres_to_gcs_staging.py:47} INFO - Uploading to bucket, department
[2024-01-07T00:26:33.782+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T00:26:33.785+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T00:26:33.838+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 61, in Postgres_To_GCS_Bucket
    gcs_hook.upload( BUCKET, gcs_path, parquet_buffer.getvalue(), 'parquet')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 541, in upload
    raise ValueError(
ValueError: 'filename' and 'data' parameter provided. Please specify a single parameter, either 'filename' for local file uploads or 'data' for file content uploads.
[2024-01-07T00:26:33.859+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_department_Postgres_To_GCS, execution_date=20231128T000000, start_date=20240107T002633, end_date=20240107T002633
[2024-01-07T00:26:33.875+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-01-07T00:26:33.875+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T00:26:33.876+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T00:26:33.889+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T00:26:33.890+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T00:26:33.891+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['franklinmutwiri41@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 61, in Postgres_To_GCS_Bucket
    gcs_hook.upload( BUCKET, gcs_path, parquet_buffer.getvalue(), 'parquet')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 541, in upload
    raise ValueError(
ValueError: 'filename' and 'data' parameter provided. Please specify a single parameter, either 'filename' for local file uploads or 'data' for file content uploads.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-07T00:26:33.924+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 360 for task copy_department_Postgres_To_GCS ('filename' and 'data' parameter provided. Please specify a single parameter, either 'filename' for local file uploads or 'data' for file content uploads.; 1890)
[2024-01-07T00:26:33.952+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-07T00:26:34.009+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T13:51:34.540+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_department_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-01-07T13:51:34.594+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_department_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-01-07T13:51:34.594+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T13:51:34.631+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_department_Postgres_To_GCS> on 2023-11-28 00:00:00+00:00
[2024-01-07T13:51:34.641+0000] {standard_task_runner.py:57} INFO - Started process 627 to run task
[2024-01-07T13:51:34.646+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_department_Postgres_To_GCS', 'scheduled__2023-11-28T00:00:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmprlch75xs']
[2024-01-07T13:51:34.650+0000] {standard_task_runner.py:85} INFO - Job 138: Subtask copy_department_Postgres_To_GCS
[2024-01-07T13:51:34.847+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_department_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T13:51:35.031+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_department_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2023-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-28T00:00:00+00:00'
[2024-01-07T13:51:35.070+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:51:35.089+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:51:35.117+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T13:51:35.123+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, department
[2024-01-07T13:51:35.124+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T13:51:35.147+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_department_Postgres_To_GCS, execution_date=20231128T000000, start_date=20240107T135134, end_date=20240107T135135
[2024-01-07T13:51:35.187+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T13:51:35.234+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T15:49:35.079+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_department_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-01-07T15:49:35.113+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_department_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-01-07T15:49:35.113+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T15:49:35.166+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_department_Postgres_To_GCS> on 2023-11-28 00:00:00+00:00
[2024-01-07T15:49:35.176+0000] {standard_task_runner.py:57} INFO - Started process 3918 to run task
[2024-01-07T15:49:35.183+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_department_Postgres_To_GCS', 'scheduled__2023-11-28T00:00:00+00:00', '--job-id', '271', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpgw74zyxi']
[2024-01-07T15:49:35.199+0000] {standard_task_runner.py:85} INFO - Job 271: Subtask copy_department_Postgres_To_GCS
[2024-01-07T15:49:35.307+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_department_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T15:49:35.458+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_department_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2023-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-28T00:00:00+00:00'
[2024-01-07T15:49:35.479+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:49:35.493+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T15:49:35.520+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T15:49:35.527+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, department
[2024-01-07T15:49:35.528+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T15:49:35.545+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_department_Postgres_To_GCS, execution_date=20231128T000000, start_date=20240107T154935, end_date=20240107T154935
[2024-01-07T15:49:35.583+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T15:49:35.613+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
