[2023-12-02T06:14:13.782+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_to_gcs_to_bq.country_load_dataset_to_bq scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-02T06:14:13.803+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_to_gcs_to_bq.country_load_dataset_to_bq scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-02T06:14:13.804+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-12-02T06:14:13.887+0000] {taskinstance.py:1382} INFO - Executing <Task(GCSToBigQueryOperator): country_load_dataset_to_bq> on 2023-12-01 00:00:00+00:00
[2023-12-02T06:14:13.898+0000] {standard_task_runner.py:57} INFO - Started process 13503 to run task
[2023-12-02T06:14:13.904+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_to_gcs_to_bq', 'country_load_dataset_to_bq', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '318', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp3cjem9pw']
[2023-12-02T06:14:13.908+0000] {standard_task_runner.py:85} INFO - Job 318: Subtask country_load_dataset_to_bq
[2023-12-02T06:14:14.129+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_to_gcs_to_bq.country_load_dataset_to_bq scheduled__2023-12-01T00:00:00+00:00 [running]> on host 40ff33dd73db
[2023-12-02T06:14:14.457+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ingest_to_gcs_to_bq' AIRFLOW_CTX_TASK_ID='country_load_dataset_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-02T06:14:14.482+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-12-02T06:14:14.485+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-12-02T06:14:14.486+0000] {gcs_to_bigquery.py:376} INFO - Using existing BigQuery table for storing data...
[2023-12-02T06:14:14.570+0000] {gcs_to_bigquery.py:380} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_NEVER', 'destinationTable': {'projectId': 'data-warehousing-proj', 'datasetId': 'staging_school', 'tableId': 'STG_COUNTRY'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://school_data_lake_data-warehousing-proj/country.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': 'true', 'encoding': 'UTF-8'}}
[2023-12-02T06:14:14.571+0000] {bigquery.py:1596} INFO - Inserting job airflow_ingest_to_gcs_to_bq_country_load_dataset_to_bq_2023_12_01T00_00_00_00_00_6a954ab5610dc89cc24b1c7925f0f3ae
[2023-12-02T06:14:14.581+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd76085b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:14.582+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7608730>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:14.587+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd76088b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:15.274+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75ad0a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:15.276+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75ad220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:15.278+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75ad3a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:17.066+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75adb20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:17.068+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75adca0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:17.069+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75ade20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:17.186+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75bb6d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:17.188+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75bb850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:17.189+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75bba30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:17.724+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75cb310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:17.726+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75cb490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:17.729+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75cb670>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:23.646+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75bb940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:23.648+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75bbd90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:23.650+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75bba30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:37.636+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75cbf10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:37.637+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75d90d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:37.639+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75d92b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:15:33.487+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75d9b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:15:33.489+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75d9cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:15:33.490+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75d9eb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:15:37.288+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75bb700>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:15:37.290+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75bba60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:15:37.291+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75bbbb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:15:55.692+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75cbbe0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:15:55.694+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75d93a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:15:55.696+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75d95e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:16:06.262+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7562790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:16:06.264+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7562910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:16:06.266+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7562af0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:17:05.275+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75d90d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:17:05.277+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75d92e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:17:05.278+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75d9520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:17:53.251+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75bb790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:17:53.252+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75bbd00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:17:53.255+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75bb460>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:18:42.439+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75713d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:18:42.441+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7571550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:18:42.442+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7571730>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:19:09.619+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_to_gcs_to_bq, task_id=country_load_dataset_to_bq, execution_date=20231201T000000, start_date=20231202T061413, end_date=20231202T061909
[2023-12-02T06:19:09.682+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-02T06:19:09.708+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
