[2024-01-07T00:26:26.381+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-01-07T00:26:26.397+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-01-07T00:26:26.397+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T00:26:26.462+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2023-11-28 00:00:00+00:00
[2024-01-07T00:26:26.500+0000] {standard_task_runner.py:57} INFO - Started process 1880 to run task
[2024-01-07T00:26:26.480+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2023-11-28T00:00:00+00:00', '--job-id', '359', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmp8tv_ge7f']
[2024-01-07T00:26:26.514+0000] {standard_task_runner.py:85} INFO - Job 359: Subtask copy_country_Postgres_To_GCS
[2024-01-07T00:26:26.798+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [running]> on host f500624b13d0
[2024-01-07T00:26:27.848+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2023-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-28T00:00:00+00:00'
[2024-01-07T00:26:27.873+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T00:26:27.921+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T00:26:27.976+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T00:26:28.131+0000] {postgres_to_gcs_staging.py:47} INFO - Uploading to bucket, country
[2024-01-07T00:26:28.540+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T00:26:28.545+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T00:26:28.676+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 61, in Postgres_To_GCS_Bucket
    gcs_hook.upload( BUCKET, gcs_path, parquet_buffer.getvalue(), 'parquet')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 541, in upload
    raise ValueError(
ValueError: 'filename' and 'data' parameter provided. Please specify a single parameter, either 'filename' for local file uploads or 'data' for file content uploads.
[2024-01-07T00:26:28.847+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20231128T000000, start_date=20240107T002626, end_date=20240107T002628
[2024-01-07T00:26:28.898+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-01-07T00:26:28.898+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T00:26:28.899+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T00:26:28.944+0000] {configuration.py:1068} WARNING - section/key [smtp/smtp_user] not found in config
[2024-01-07T00:26:28.944+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-01-07T00:26:28.945+0000] {taskinstance.py:2007} ERROR - Failed to send email to: ['franklinmutwiri41@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/postgres_to_gcs_staging.py", line 61, in Postgres_To_GCS_Bucket
    gcs_hook.upload( BUCKET, gcs_path, parquet_buffer.getvalue(), 'parquet')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 541, in upload
    raise ValueError(
ValueError: 'filename' and 'data' parameter provided. Please specify a single parameter, either 'filename' for local file uploads or 'data' for file content uploads.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-01-07T00:26:29.313+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 359 for task copy_country_Postgres_To_GCS ('filename' and 'data' parameter provided. Please specify a single parameter, either 'filename' for local file uploads or 'data' for file content uploads.; 1880)
[2024-01-07T00:26:29.361+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-07T00:26:29.425+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T13:48:30.975+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-01-07T13:48:31.019+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-01-07T13:48:31.019+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T13:48:31.059+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2023-11-28 00:00:00+00:00
[2024-01-07T13:48:31.073+0000] {standard_task_runner.py:57} INFO - Started process 524 to run task
[2024-01-07T13:48:31.077+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2023-11-28T00:00:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpnqg_iyz1']
[2024-01-07T13:48:31.087+0000] {standard_task_runner.py:85} INFO - Job 129: Subtask copy_country_Postgres_To_GCS
[2024-01-07T13:48:31.219+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T13:48:31.403+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2023-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-28T00:00:00+00:00'
[2024-01-07T13:48:31.423+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:48:31.440+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:48:31.461+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T13:48:31.468+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T13:48:31.543+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-07T13:48:31.552+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-07T13:48:34.512+0000] {gcs.py:576} INFO - Data stream uploaded to data/country.parquet in school_data_lake_data-warehousing-proj bucket
[2024-01-07T13:48:34.524+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-01-07T13:48:34.571+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:48:34.597+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T13:48:34.597+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T13:48:34.614+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20231128T000000, start_date=20240107T134830, end_date=20240107T134834
[2024-01-07T13:48:34.705+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T13:48:34.735+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-01-07T13:51:27.399+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-01-07T13:51:27.424+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2024-01-07T13:51:27.424+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2024-01-07T13:51:27.453+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): copy_country_Postgres_To_GCS> on 2023-11-28 00:00:00+00:00
[2024-01-07T13:51:27.461+0000] {standard_task_runner.py:57} INFO - Started process 608 to run task
[2024-01-07T13:51:27.467+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_from_postgres_to_GCS_bucket', 'copy_country_Postgres_To_GCS', 'scheduled__2023-11-28T00:00:00+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpcmmne46v']
[2024-01-07T13:51:27.470+0000] {standard_task_runner.py:85} INFO - Job 134: Subtask copy_country_Postgres_To_GCS
[2024-01-07T13:51:27.557+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_from_postgres_to_GCS_bucket.copy_country_Postgres_To_GCS scheduled__2023-11-28T00:00:00+00:00 [running]> on host 5d007c0b4985
[2024-01-07T13:51:27.706+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_from_postgres_to_GCS_bucket' AIRFLOW_CTX_TASK_ID='copy_country_Postgres_To_GCS' AIRFLOW_CTX_EXECUTION_DATE='2023-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-28T00:00:00+00:00'
[2024-01-07T13:51:27.724+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:51:27.741+0000] {base.py:73} INFO - Using connection ID 'postgres_docker_conn' for task execution.
[2024-01-07T13:51:27.761+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-01-07T13:51:27.769+0000] {postgres_to_gcs_staging.py:52} INFO - Uploading to bucket, country
[2024-01-07T13:51:27.770+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-07T13:51:27.788+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_from_postgres_to_GCS_bucket, task_id=copy_country_Postgres_To_GCS, execution_date=20231128T000000, start_date=20240107T135127, end_date=20240107T135127
[2024-01-07T13:51:27.840+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-07T13:51:27.867+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
