[2023-12-02T06:14:14.147+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_to_gcs_to_bq.course_load_dataset_to_bq scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-02T06:14:14.168+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_to_gcs_to_bq.course_load_dataset_to_bq scheduled__2023-12-01T00:00:00+00:00 [queued]>
[2023-12-02T06:14:14.168+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-12-02T06:14:14.309+0000] {taskinstance.py:1382} INFO - Executing <Task(GCSToBigQueryOperator): course_load_dataset_to_bq> on 2023-12-01 00:00:00+00:00
[2023-12-02T06:14:14.324+0000] {standard_task_runner.py:57} INFO - Started process 13504 to run task
[2023-12-02T06:14:14.334+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ingest_to_gcs_to_bq', 'course_load_dataset_to_bq', 'scheduled__2023-12-01T00:00:00+00:00', '--job-id', '319', '--raw', '--subdir', 'DAGS_FOLDER/postgres_to_gcs_staging.py', '--cfg-path', '/tmp/tmpdhv3aje6']
[2023-12-02T06:14:14.340+0000] {standard_task_runner.py:85} INFO - Job 319: Subtask course_load_dataset_to_bq
[2023-12-02T06:14:14.560+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_to_gcs_to_bq.course_load_dataset_to_bq scheduled__2023-12-01T00:00:00+00:00 [running]> on host 40ff33dd73db
[2023-12-02T06:14:14.884+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinmutwiri41@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ingest_to_gcs_to_bq' AIRFLOW_CTX_TASK_ID='course_load_dataset_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T00:00:00+00:00'
[2023-12-02T06:14:14.908+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-12-02T06:14:14.913+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-12-02T06:14:14.914+0000] {gcs_to_bigquery.py:376} INFO - Using existing BigQuery table for storing data...
[2023-12-02T06:14:14.977+0000] {gcs_to_bigquery.py:380} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_NEVER', 'destinationTable': {'projectId': 'data-warehousing-proj', 'datasetId': 'staging_school', 'tableId': 'STG_COURSE'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://school_data_lake_data-warehousing-proj/course.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': 'true', 'encoding': 'UTF-8'}}
[2023-12-02T06:14:14.979+0000] {bigquery.py:1596} INFO - Inserting job airflow_ingest_to_gcs_to_bq_course_load_dataset_to_bq_2023_12_01T00_00_00_00_00_e50f090ea7eef422a6772578f3c36f9f
[2023-12-02T06:14:14.996+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd76b8dc0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:14.998+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7609e50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:15.000+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75ad070>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:15.470+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75ad7c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:15.471+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75ad940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:15.473+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75adac0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:15.519+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7609f10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:15.521+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7609ee0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:15.523+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75ade50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:16.830+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75ba280>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:16.833+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75ba400>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:16.835+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75ba580>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:19.869+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75badc0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:19.870+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75baf40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:19.872+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75c7160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:24.623+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd76094c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:24.625+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7609e80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:24.626+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7609f70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:48.268+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75c7a00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:48.310+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75c7b80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:14:48.312+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75c7d60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:15:29.707+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75d5640>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:15:29.709+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75d57c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:15:29.711+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75d59a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:16:07.767+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75adfa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:16:07.768+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75ade20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:16:07.770+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75baa00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:16:46.864+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7564280>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:16:46.871+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7564400>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:16:46.873+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75645e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:16:52.269+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7564e80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:16:52.296+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7571040>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:16:52.298+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75d5d00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:17:13.462+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7609eb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:17:13.465+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7609940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:17:13.467+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7571250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:17:47.275+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7571ac0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:17:47.277+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7571c40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:17:47.278+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7571e20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:18:27.353+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd757f700>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:18:27.355+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7571460>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:18:27.357+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd75714c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:18:37.888+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd7564ac0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:18:37.891+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd757f8e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:18:37.892+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8bd757fa60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-12-02T06:19:44.417+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ingest_to_gcs_to_bq, task_id=course_load_dataset_to_bq, execution_date=20231201T000000, start_date=20231202T061414, end_date=20231202T061944
[2023-12-02T06:19:44.590+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-02T06:19:44.625+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
